services:
  ctr-haos:
    image: homeassistant/home-assistant:stable
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    # Recomendado pelo Home Assistant para detectar dispositivos na rede
    network_mode: host

    # Necess√°rio para acessar dispositivos USB, BLE, Bluetooth Proxy
    privileged: true

    volumes:
      - ${VOL_CONFIG}
      - ${VOL_TZ}
      - ${VOL_LOCALTIME}

    environment:
      - TZ=${TZ}
